### ISSUE TITLE
issue with ktor 1.0, Kotlin 1.3

### ISSUE THREAD

**Issue by rburgst** [rharter/ktor-moshi#3]
I created a sample ktor project with gson and then added Moshi (and deleted gson)

I added the following dependencies

```groovy
    compile 'com.ryanharter.ktor:ktor-moshi:1.0.0'
    implementation 'com.squareup.moshi:moshi-adapters:1.8.0'
```

Setup the plugin (note that I removed gson)
```
    install(ContentNegotiation) {
        moshi {
            add(Date::class.java, Rfc3339DateJsonAdapter())
        }
    }
```

When I invoke the gson endpoint
```kotlin
routing {
        get("/json/gson") {
            call.respond(mapOf("hello" to "world"))
        }
```
Then I get the following error:
```
java.lang.AbstractMethodError: com.ryanharter.ktor.moshi.MoshiConverter.convertForSend(Lio/ktor/util/pipeline/PipelineContext;Lio/ktor/http/ContentType;Ljava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
	at io.ktor.features.ContentNegotiation$Feature$install$2.invokeSuspend(ContentNegotiation.kt:82)
	at io.ktor.features.ContentNegotiation$Feature$install$2.invoke(ContentNegotiation.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:248)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:63)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:111)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:131)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:24)
	at com.burgstaller.ktor.ApplicationKt$module$9$8.invokeSuspend(Application.kt:154)
```

**Comment by rburgst** [comment]
Sample project is here: 
https://github.com/rburgst/ktor-moshi-issue

**Comment by rburgst** [comment]
hmm, looks like https://github.com/rharter/ktor-moshi/pull/2 should fix this. I would love to see a merged release.

**Comment by rburgst** [comment]
have tried the PR and can confirm that its working there. I am fairly certain that the problem is that ktor-moshi 1.0.0 uses the experimental coroutine support while in 1.3 its official and probably not binary compatible.

**Comment by rharter** [comment]
Release 1.0.1 is on it's way.

**Comment by rburgst** [comment]
on search.maven.org its still 1.0.0

https://search.maven.org/search?q=a:ktor-moshi

**Comment by rharter** [comment]
Thanks for identifying, @rburgst. Had a signing issue I was working through.  Should be up and running, now.
